language: node_js
node_js:
  - "node"
# Not needed with `npm ci`
# cache:
#   directories:
#   - node_modules/
#   - functions/node_modules/

install:
  - npm ci
  - cd ./functions && npm ci && cd ..

script:
  - npm run test:unit
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then npm run build-staging; fi

deploy:
  - provider: script
    script: 
     - npm i -g firebase-tools
     - firebase deploy --token $FIREBASE_DEPLOY_KEY --project prod
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: 
     - npm i -g firebase-tools
     - firebase deploy --token $FIREBASE_DEPLOY_KEY --project staging
    skip_cleanup: true
    on:
      branch: develop
