language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules/
  - functions/node_modules/

before_install:
  - npm i -g npm@5.7.1 # this should be deleted once 5.7.X is out of "pre-release"

install:
  - npm ci
  - cd ./functions && npm ci && cd ..

branches:
  only:
    - master
    script:
      - npm run build

branches:
  except:
    - master
    script:
      - npm run dev-build

deploy:
  - provider: firebase
    token: $FIREBASE_DEPLOY_KEY
    project: "prod"
    skip_cleanup: true
    on:
      branch: master
  - provider: firebase
    token: $FIREBASE_DEPLOY_KEY
    project: "dev"
    skip_cleanup: true
    on:
      branch: develop
